# User Credentials
email: email@domain.com
username: user
password: pass

# Strategy to use when wagering. Options are as follows.
#  constant : Wager a constant value. All-in if balance is lower than constant value.
#  all-in : Wager full account balance.
#  percentage : Wager a percentage of the account balance.
wager_strategy: percentage

# Constant amount to wager when using the constant wager strategy.
# This must be a whole number greater than 0.
constant_wager: 200

# Percent of account balance to wager when using the constant wager strategy.
# This must be a decimal value greater than 0 and less than 1
percentage_wager: 0.2